<?php // generated by Nette 
return array(
	'debugMode' => TRUE,
	'modules' => array(
		'forms' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'FormsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/forms-module',
			'autoload' => array(
				'psr-0' => array(
					'FormsModule' => '',
				),
			),
			'require' => array(
				'assets' => '2.1.x',
			),
		),
		'translator' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'TranslatorModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/translator-module',
			'autoload' => array(
				'psr-0' => array(
					'TranslatorModule' => '',
				),
			),
			'require' => array(),
		),
		'assets' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'AssetsModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/assets-module',
			'autoload' => array(
				'psr-0' => array(
					'AssetsModule' => '',
				),
			),
			'require' => array(),
		),
		'doctrine' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'DoctrineModule\\Module',
			'version' => '2.1.0',
			'path' => '%libsDir%/venne/doctrine-module',
			'autoload' => array(
				'psr-0' => array(
					'DoctrineModule' => '',
				),
			),
			'require' => array(
				'forms' => '2.1.x',
			),
		),
		'cms' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'CmsModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/..',
			'autoload' => array(
				'psr-0' => array(
					'CmsModule' => '',
				),
				'files' => array(),
			),
			'require' => array(
				'doctrine' => '2.0.x',
				'assets' => '2.0.x',
				'translator' => '2.0.x',
			),
		),
		'jquery2.0' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'JQueryModule\\Module',
			'version' => '2.0.0',
			'path' => '%libsDir%/venne/jquery2.0-module',
			'autoload' => array(),
			'require' => array(),
		),
		'jqueryui1.10' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'JQueryui1_10Module\\Module',
			'version' => '1.10.0',
			'path' => '%libsDir%/venne/jqueryui1.10-module',
			'autoload' => array(),
			'require' => array(),
		),
		'bootstrap2' => array(
			'status' => 'installed',
			'action' => '',
			'class' => 'Bootstrap2Module\\Module',
			'version' => '2.3.0',
			'path' => '%libsDir%/venne/bootstrap2-module',
			'autoload' => array(),
			'require' => array(),
		),
	),
);